#!/bin/bash

TOMCAT_HOME=/opt/billPayApp
WEBAPP_LOCATION=$TOMCAT_HOME/webapps

TMP_DIR=$TOMCAT_HOME/temp
WORK_DIR=$TOMCAT_HOME/work

CATALINA_SH_PATH=/etc/init.d/billPayApp

SERVICE_NAME=billPayApp
START_SCRIPT="service $SERVICE_NAME start"
STOP_SCRIPT="service $SERVICE_NAME stop"
STATUS_SCRIPT="service $SERVICE_NAME status"

PID_FILE=billPayApp
CONTEXT_NAME=ROOT

#Version is passed by a user from Jenkins job
WAR_URL=http://prod-nexus-int.pageonce.net:8081/nexus/service/local/artifact/maven/content?g=com.intuit.billpay&a=billpay-webapp&r=releases&p=war&v=

