#!/bin/bash

export TOMCAT_HOME=/opt/export-tomcat-app
export WEBAPP_LOCATION=$TOMCAT_HOME/webapps

export TMP_DIR=$TOMCAT_HOME/temp
export WORK_DIR=$TOMCAT_HOME/work

export CATALINA_SH_PATH=/etc/init.d/export-tomcat-app

export SERVICE_NAME=export-tomcat-app
export START_SCRIPT="service $SERVICE_NAME start"
export STOP_SCRIPT="service $SERVICE_NAME stop"
export STATUS_SCRIPT="service $SERVICE_NAME status"

export PID_FILE=export-tomcat-app
export CONTEXT_NAME=ROOT

#Version is passed by a user from Jenkins job
export WAR_URL='https://nexus.com/nexus/service/local/artifact/maven/content?g=com.mycompany.myorg&a=export-tomcat-app-webapp&r=releases&p=war&v='
