#!/bin/bash

TOMCAT_HOME=/opt/haskyAdmin
WEBAPP_LOCATION=$TOMCAT_HOME/webapps

TMP_DIR=$TOMCAT_HOME/temp
WORK_DIR=$TOMCAT_HOME/work

CATALINA_SH_PATH=/etc/init.d/tomcat6

SERVICE_NAME=tomcat6
START_SCRIPT="/sbin/service $SERVICE_NAME start"
STOP_SCRIPT="/sbin/service $SERVICE_NAME stop"
STATUS_SCRIPT="/sbin/service $SERVICE_NAME status"

PID_FILE=tomcat6
CONTEXT_NAME=ROOT

#Version is passed by a user from Jenkins job
WAR_URL=https://nj1-28-2-nexus.nj.check.local/nexus/service/local/artifact/maven/content?g=com.intuit.mintbills.hasky&a=hasky-admin&r=releases&p=war&v=
