#!/bin/bash

TOMCAT_HOME=/opt/apache-tomcat-7.0.64
WEBAPP_LOCATION=$TOMCAT_HOME/webapps
TMP_DIR=$TOMCAT_HOME/webapps
WORK_DIR=$TOMCAT_HOME/work
START_SCRIPT="$TOMCAT_HOME/bin/catalina.sh start"
STOP_SCRIPT="$TOMCAT_HOME/bin/catalina.sh stop"

STATUS_SCRIPT="ps -ef | grep Bootstrap | wc -l"
MY_SCRIPT="echo kuku"
CONTEXT_NAME=kuku
WAR_URL="http://avalon:8081/nexus/service/local/artifact/maven/content?g=com.intuit.mintbills&a=horizon-webapp&v=1.0.0&r=releases&p=war"


