#!/bin/bash

TOMCAT_HOME=/opt/platform-service
WEBAPP_LOCATION=$TOMCAT_HOME/webapps

TMP_DIR=$TOMCAT_HOME/temp
WORK_DIR=$TOMCAT_HOME/work
CATALINA_SH_PATH=/etc/init.d/platform-service

SERVICE_NAME=platform-service
START_SCRIPT="service $SERVICE_NAME start"
STOP_SCRIPT="service $SERVICE_NAME stop"
STATUS_SCRIPT="service $SERVICE_NAME status"

PID_FILE=platform-service
CONTEXT_NAME=ROOT

#TODO version as a parameter passed by user from Jenkins job
WAR_URL=https://nj1-28-2-nexus.nj.check.local/nexus/service/local/artifact/maven/content?g=com.intuit.mintbills&a=platform-webapp&r=releases&p=war&v=
