#!/bin/bash

TOMCAT_HOME=/opt/someapp
WEBAPP_LOCATION=$TOMCAT_HOME/webapps

TMP_DIR=$TOMCAT_HOME/temp
WORK_DIR=$TOMCAT_HOME/work

CATALINA_SH_PATH=/etc/init.d/someapp

SERVICE_NAME=someapp
START_SCRIPT="service $SERVICE_NAME start"
STOP_SCRIPT="service $SERVICE_NAME stop"
STATUS_SCRIPT="service $SERVICE_NAME status"

PID_FILE=someapp
CONTEXT_NAME=ROOT

#TODO version as a parameter passed by user from Jenkins job
WAR_URL=https://nexus.net/nexus/service/local/artifact/maven/content?g=com.mycompany.someorg&a=someapp-webapp&r=releases&p=war&v=
